using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;

if (args.Length > 0 && (args[0] == "-h" || args[0] == "--help"))
{
    await Console.Out.WriteLineAsync("Usage: Habitinator.Diagrams [repoRoot] [outputDir]");
    await Console.Out.WriteLineAsync("  Default repoRoot: current directory");
    await Console.Out.WriteLineAsync("  Default outputDir: {repoRoot}/artifacts/diagrams");
    return;
}

var repoRoot = Path.GetFullPath(args.Length > 0 ? args[0] : Directory.GetCurrentDirectory());
var outDir = Path.GetFullPath(args.Length > 1 ? args[1] : Path.Combine(repoRoot, "artifacts", "diagrams"));
Directory.CreateDirectory(outDir);

var slnxPath = Path.Combine(repoRoot, "Habitinator.slnx");

if (!File.Exists(slnxPath))
{
    await Console.Error.WriteLineAsync($"Solution not found: {slnxPath}");
    Environment.Exit(1);
}

await File.WriteAllTextAsync(Path.Combine(outDir, "solution-graph.mmd"), BuildSolutionMermaid(slnxPath, repoRoot), Encoding.UTF8);
await Console.Out.WriteLineAsync($"Wrote {Path.Combine(outDir, "solution-graph.mmd")}");

static string BuildSolutionMermaid(string slnxPath, string repoRoot)
{
    var doc = XDocument.Load(slnxPath, LoadOptions.None);
    var projectPaths = doc.Descendants()
        .Select(e => e.Attribute("Path")?.Value)
        .OfType<string>()
        .Select(p => p.Replace('\\', Path.DirectorySeparatorChar))
        .ToList();

    var nodes = ParseProjects(projectPaths, repoRoot);
    var edges = ParseProjectEdges(nodes);

    var sb = new StringBuilder();
    sb.AppendLine("flowchart LR");
    sb.AppendLine("%% Auto-generated by tools/Habitinator.Diagrams (project reference graph)");
    foreach (var name in nodes.Values.Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(s => s, StringComparer.OrdinalIgnoreCase))
    {
        sb.AppendLine(CultureInfo.InvariantCulture, $"  {SanitizeMermaidId(name)}[\"{EscapeMermaidLabel(name)}\"]");
    }

    foreach (var (from, to) in edges.OrderBy(e => e.From, StringComparer.OrdinalIgnoreCase).ThenBy(e => e.To, StringComparer.OrdinalIgnoreCase))
    {
        sb.AppendLine(CultureInfo.InvariantCulture, $"  {SanitizeMermaidId(from)} --> {SanitizeMermaidId(to)}");
    }

    return sb.ToString();
}

static Dictionary<string, string> ParseProjects(IEnumerable<string> projectPaths, string repoRoot)
{
    var nodes = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
    foreach (var rel in projectPaths)
    {
        var full = Path.GetFullPath(Path.Combine(repoRoot, rel));
        if (File.Exists(full))
        {
            nodes[full] = Path.GetFileNameWithoutExtension(full);
        }
    }
    return nodes;
}

static List<(string From, string To)> ParseProjectEdges(Dictionary<string, string> nodes)
{
    var edges = new List<(string From, string To)>();
    foreach (var (fullPath, _) in nodes)
    {
        ParseProjectFileEdges(fullPath, nodes, edges);
    }
    return edges;
}

static void ParseProjectFileEdges(string fullPath, Dictionary<string, string> nodes, List<(string From, string To)> edges)
{
    foreach (var line in File.ReadAllLines(fullPath))
    {
        var m = Regex.Match(line, @"<ProjectReference\s+Include=""([^""]+)""", RegexOptions.None, TimeSpan.FromSeconds(1));
        if (!m.Success)
        {
            continue;
        }

        var refRel = m.Groups[1].Value.Replace('\\', Path.DirectorySeparatorChar);
        var dir = Path.GetDirectoryName(fullPath) ?? Directory.GetCurrentDirectory();
        var refFull = Path.GetFullPath(Path.Combine(dir, refRel));
        if (nodes.TryGetValue(refFull, out var toName) && nodes.TryGetValue(fullPath, out var fromName))
        {
            edges.Add((fromName, toName));
        }
    }
}

static string SanitizeMermaidId(string name)
{
    var s = Regex.Replace(name, @"[^\w]", "_", RegexOptions.None, TimeSpan.FromSeconds(1));
    if (string.IsNullOrEmpty(s) || char.IsDigit(s[0]))
    {
        s = "P_" + s;
    }
    return s;
}

static string EscapeMermaidLabel(string name) => name.Replace("\"", "'");
