using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;

if (args.Length > 0 && (args[0] == "-h" || args[0] == "--help"))
{
    Console.WriteLine("Usage: Habitinator.Diagrams [repoRoot] [outputDir]");
    Console.WriteLine("  Default repoRoot: current directory");
    Console.WriteLine("  Default outputDir: {repoRoot}/artifacts/diagrams");
    return;
}

var repoRoot = Path.GetFullPath(args.Length > 0 ? args[0] : Directory.GetCurrentDirectory());
var outDir = Path.GetFullPath(args.Length > 1 ? args[1] : Path.Combine(repoRoot, "artifacts", "diagrams"));
Directory.CreateDirectory(outDir);

var slnxPath = Path.Combine(repoRoot, "Habitinator.slnx");
var snapshotPath = Path.Combine(repoRoot, "src", "App.Web", "Data", "Migrations", "ApplicationDbContextModelSnapshot.cs");

if (!File.Exists(slnxPath))
{
    Console.Error.WriteLine($"Solution not found: {slnxPath}");
    Environment.Exit(1);
}

await File.WriteAllTextAsync(Path.Combine(outDir, "solution-graph.mmd"), BuildSolutionMermaid(slnxPath, repoRoot), Encoding.UTF8);
Console.WriteLine($"Wrote {Path.Combine(outDir, "solution-graph.mmd")}");

if (File.Exists(snapshotPath))
{
    await File.WriteAllTextAsync(Path.Combine(outDir, "database-schema.mmd"), BuildErMermaid(snapshotPath), Encoding.UTF8);
    Console.WriteLine($"Wrote {Path.Combine(outDir, "database-schema.mmd")}");
}
else
{
    Console.WriteLine($"Skip ER diagram (snapshot missing): {snapshotPath}");
}

static string BuildSolutionMermaid(string slnxPath, string repoRoot)
{
    var doc = XDocument.Load(slnxPath, LoadOptions.None);
    var projectPaths = doc.Descendants()
        .Where(e => e.Name.LocalName == "Project" && e.Attribute("Path") is not null)
        .Select(e => e.Attribute("Path")!.Value.Replace('\\', Path.DirectorySeparatorChar))
        .ToList();

    var nodes = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
    foreach (var rel in projectPaths)
    {
        var full = Path.GetFullPath(Path.Combine(repoRoot, rel));
        if (!File.Exists(full)) continue;
        var name = Path.GetFileNameWithoutExtension(full);
        nodes[full] = name;
    }

    var edges = new List<(string From, string To)>();
    foreach (var (fullPath, _) in nodes)
    {
        foreach (var line in File.ReadAllLines(fullPath))
        {
            var m = Regex.Match(line, @"<ProjectReference\s+Include=""([^""]+)""");
            if (!m.Success) continue;
            var refRel = m.Groups[1].Value.Replace('\\', Path.DirectorySeparatorChar);
            var refFull = Path.GetFullPath(Path.Combine(Path.GetDirectoryName(fullPath)!, refRel));
            if (nodes.TryGetValue(refFull, out var toName) && nodes.TryGetValue(fullPath, out var fromName))
                edges.Add((fromName, toName));
        }
    }

    var sb = new StringBuilder();
    sb.AppendLine("%% Auto-generated by tools/Habitinator.Diagrams — project reference graph");
    sb.AppendLine("flowchart LR");
    foreach (var name in nodes.Values.Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(s => s, StringComparer.OrdinalIgnoreCase))
        sb.AppendLine($"  {SanitizeMermaidId(name)}[\"{EscapeMermaidLabel(name)}\"]");

    foreach (var (from, to) in edges.OrderBy(e => e.From, StringComparer.OrdinalIgnoreCase).ThenBy(e => e.To, StringComparer.OrdinalIgnoreCase))
        sb.AppendLine($"  {SanitizeMermaidId(from)} --> {SanitizeMermaidId(to)}");

    return sb.ToString();
}

static string SanitizeMermaidId(string name)
{
    var s = Regex.Replace(name, @"[^\w]", "_");
    if (string.IsNullOrEmpty(s) || char.IsDigit(s[0])) s = "P_" + s;
    return s;
}

static string EscapeMermaidLabel(string name) => name.Replace("\"", "'");

static string BuildErMermaid(string snapshotPath)
{
    var content = File.ReadAllText(snapshotPath);
    var tableByType = new Dictionary<string, string>(StringComparer.Ordinal);
    var relationships = new List<(string ChildType, string ParentType)>();

    foreach (var (type, body) in SplitEntityBlocks(content))
    {
        var tm = Regex.Match(body, @"\.ToTable\(""([^""]+)""");
        if (tm.Success) tableByType[type] = tm.Groups[1].Value;

        foreach (Match hm in Regex.Matches(body, @"b\.HasOne\(""([^""]+)""[\s\S]*?\.HasForeignKey\(""([^""]+)""\)", RegexOptions.None))
        {
            var parentType = hm.Groups[1].Value;
            relationships.Add((type, parentType));
        }
    }

    var sb = new StringBuilder();
    sb.AppendLine("%% Auto-generated from EF Core ApplicationDbContextModelSnapshot");
    sb.AppendLine("erDiagram");

    foreach (var (childType, parentType) in relationships)
    {
        if (!tableByType.TryGetValue(childType, out var childTable)) continue;
        if (!tableByType.TryGetValue(parentType, out var parentTable)) continue;
        if (string.Equals(childTable, parentTable, StringComparison.Ordinal)) continue;
        sb.AppendLine($"  {QuoteErTable(parentTable)} ||--o{{ {QuoteErTable(childTable)} : \"fk\"");
    }

    return sb.ToString();
}

/// <summary>Mermaid erDiagram requires unquoted identifiers or quoted labels; use backtick-safe names.</summary>
static string QuoteErTable(string table) =>
    Regex.IsMatch(table, @"^[\w]+$") ? table : $"\"{table.Replace("\"", "'")}\"";

static IEnumerable<(string Type, string Body)> SplitEntityBlocks(string content)
{
    const string prefix = "modelBuilder.Entity(\"";
    var idx = 0;
    while (true)
    {
        var start = content.IndexOf(prefix, idx, StringComparison.Ordinal);
        if (start < 0) yield break;
        start += prefix.Length;
        var typeEnd = content.IndexOf('"', start);
        if (typeEnd < 0) yield break;
        var type = content[start..typeEnd];
        var braceStart = content.IndexOf('{', typeEnd);
        if (braceStart < 0) yield break;
        var endBrace = FindMatchingBrace(content, braceStart);
        if (endBrace < 0) yield break;
        var body = content[braceStart..(endBrace + 1)];
        yield return (type, body);
        idx = endBrace + 1;
    }
}

static int FindMatchingBrace(string s, int openIdx)
{
    var depth = 0;
    for (var i = openIdx; i < s.Length; i++)
    {
        if (s[i] == '{') depth++;
        else if (s[i] == '}')
        {
            depth--;
            if (depth == 0) return i;
        }
    }

    return -1;
}
