using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;

if (args.Length > 0 && (args[0] == "-h" || args[0] == "--help"))
{
    await Console.Out.WriteLineAsync("Usage: Habitinator.Diagrams [repoRoot] [outputDir]");
    await Console.Out.WriteLineAsync("  Default repoRoot: current directory");
    await Console.Out.WriteLineAsync("  Default outputDir: {repoRoot}/artifacts/diagrams");
    return;
}

var repoRoot = Path.GetFullPath(args.Length > 0 ? args[0] : Directory.GetCurrentDirectory());
var outDir = Path.GetFullPath(args.Length > 1 ? args[1] : Path.Combine(repoRoot, "artifacts", "diagrams"));
Directory.CreateDirectory(outDir);

var slnxPath = Path.Combine(repoRoot, "Habitinator.slnx");
var snapshotPath = Path.Combine(repoRoot, "src", "App.Web", "Data", "Migrations", "ApplicationDbContextModelSnapshot.cs");

if (!File.Exists(slnxPath))
{
    await Console.Error.WriteLineAsync($"Solution not found: {slnxPath}");
    Environment.Exit(1);
}

await File.WriteAllTextAsync(Path.Combine(outDir, "solution-graph.mmd"), BuildSolutionMermaid(slnxPath, repoRoot), Encoding.UTF8);
await Console.Out.WriteLineAsync($"Wrote {Path.Combine(outDir, "solution-graph.mmd")}");

if (File.Exists(snapshotPath))
{
    await File.WriteAllTextAsync(Path.Combine(outDir, "database-schema.mmd"), BuildErMermaid(snapshotPath), Encoding.UTF8);
    await Console.Out.WriteLineAsync($"Wrote {Path.Combine(outDir, "database-schema.mmd")}");
}
else
{
    await Console.Out.WriteLineAsync($"Skip ER diagram (snapshot missing): {snapshotPath}");
}

static string BuildSolutionMermaid(string slnxPath, string repoRoot)
{
    var doc = XDocument.Load(slnxPath, LoadOptions.None);
    var projectPaths = doc.Descendants()
        .Where(e => e.Name.LocalName == "Project" && e.Attribute("Path") is not null)
            .Select(e => e.Attribute("Path").Value.Replace('\\', Path.DirectorySeparatorChar))
        .ToList();

    var nodes = ParseProjects(projectPaths, repoRoot);
    var edges = ParseProjectEdges(nodes);

    var sb = new StringBuilder();
    sb.AppendLine("flowchart LR");
    sb.AppendLine("%% Auto-generated by tools/Habitinator.Diagrams (project reference graph)");
    foreach (var name in nodes.Values.Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(s => s, StringComparer.OrdinalIgnoreCase))
        sb.AppendLine($"  {SanitizeMermaidId(name)}[\"{EscapeMermaidLabel(name)}\"]");

    foreach (var (from, to) in edges.OrderBy(e => e.From, StringComparer.OrdinalIgnoreCase).ThenBy(e => e.To, StringComparer.OrdinalIgnoreCase))
        sb.AppendLine($"  {SanitizeMermaidId(from)} --> {SanitizeMermaidId(to)}");

    return sb.ToString();
}

static Dictionary<string, string> ParseProjects(IEnumerable<string> projectPaths, string repoRoot)
{
    var nodes = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
    foreach (var rel in projectPaths)
    {
        var full = Path.GetFullPath(Path.Combine(repoRoot, rel));
        if (File.Exists(full))
        {
            nodes[full] = Path.GetFileNameWithoutExtension(full);
        }
    }
    return nodes;
}

static List<(string From, string To)> ParseProjectEdges(Dictionary<string, string> nodes)
{
    var edges = new List<(string From, string To)>();
    foreach (var (fullPath, _) in nodes)
    {
        ParseProjectFileEdges(fullPath, nodes, edges);
    }
    return edges;
}

static void ParseProjectFileEdges(string fullPath, Dictionary<string, string> nodes, List<(string From, string To)> edges)
{
    foreach (var line in File.ReadAllLines(fullPath))
    {
        var m = Regex.Match(line, @"<ProjectReference\s+Include=""([^""]+)""");
        if (!m.Success) continue;

        var refRel = m.Groups[1].Value.Replace('\\', Path.DirectorySeparatorChar);
        var refFull = Path.GetFullPath(Path.Combine(Path.GetDirectoryName(fullPath)!, refRel));
        if (nodes.TryGetValue(refFull, out var toName) && nodes.TryGetValue(fullPath, out var fromName))
        {
            edges.Add((fromName, toName));
        }
    }
}

static string SanitizeMermaidId(string name)
{
    var s = Regex.Replace(name, @"[^\w]", "_");
    if (string.IsNullOrEmpty(s) || char.IsDigit(s[0])) s = "P_" + s;
    return s;
}

static string EscapeMermaidLabel(string name) => name.Replace("\"", "'");

static string BuildErMermaid(string snapshotPath)
{
    var content = File.ReadAllText(snapshotPath);
    var tableByType = new Dictionary<string, string>(StringComparer.Ordinal);
    var relationships = new List<(string ChildType, string ParentType)>();

    foreach (var (type, body) in SplitEntityBlocks(content))
    {
        var tm = Regex.Match(body, @"\.ToTable\(""([^""]+)""");
        if (tm.Success) tableByType[type] = tm.Groups[1].Value;

        foreach (Match hm in Regex.Matches(body, @"b\.HasOne\(""([^""]+)""[\s\S]*?\.HasForeignKey\(""([^""]+)""\)", RegexOptions.None))
        {
            var parentType = hm.Groups[1].Value;
            relationships.Add((type, parentType));
        }
    }

    var edges = new List<(string ParentTable, string ChildTable)>();
    foreach (var (childType, parentType) in relationships)
    {
        if (!tableByType.TryGetValue(childType, out var childTable)) continue;
        if (!tableByType.TryGetValue(parentType, out var parentTable)) continue;
        if (string.Equals(childTable, parentTable, StringComparison.Ordinal)) continue;
        edges.Add((parentTable, childTable));
    }

    edges = edges
        .Distinct()
        .OrderBy(e => e.ParentTable, StringComparer.Ordinal)
        .ThenBy(e => e.ChildTable, StringComparer.Ordinal)
        .ToList();

    var tableNames = new SortedSet<string>(StringComparer.Ordinal);
    foreach (var (p, c) in edges)
    {
        tableNames.Add(p);
        tableNames.Add(c);
    }

    var sb = new StringBuilder();
    sb.AppendLine("flowchart TB");
    sb.AppendLine("%% Auto-generated from EF Core ApplicationDbContextModelSnapshot");

    foreach (var t in tableNames)
        sb.AppendLine($"  {SanitizeMermaidId(t)}[\"{EscapeMermaidLabel(t)}\"]");

    foreach (var (parentTable, childTable) in edges)
        sb.AppendLine($"  {SanitizeMermaidId(parentTable)} -->|fk| {SanitizeMermaidId(childTable)}");

    return sb.ToString();
}

static IEnumerable<(string Type, string Body)> SplitEntityBlocks(string content)
{
    const string prefix = "modelBuilder.Entity(\"";
    var idx = 0;
    while (true)
    {
        var start = content.IndexOf(prefix, idx, StringComparison.Ordinal);
        if (start < 0) yield break;
        start += prefix.Length;
        var typeEnd = content.IndexOf('"', start);
        if (typeEnd < 0) yield break;
        var type = content[start..typeEnd];
        var braceStart = content.IndexOf('{', typeEnd);
        if (braceStart < 0) yield break;
        var endBrace = FindMatchingBrace(content, braceStart);
        if (endBrace < 0) yield break;
        var body = content[braceStart..(endBrace + 1)];
        yield return (type, body);
        idx = endBrace + 1;
    }
}

static int FindMatchingBrace(string s, int openIdx)
{
    var depth = 0;
    for (var i = openIdx; i < s.Length; i++)
    {
        if (s[i] == '{') depth++;
        else if (s[i] == '}')
        {
            depth--;
            if (depth == 0) return i;
        }
    }

    return -1;
}
